<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\mpalc\OneDrive\Desktop\_projects\Venezia 2025\venezia-2025\static\models\undertow\Bull_02.glb -t -i
-->
<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		fallback,
		error,
		children
	}: {
		children?: Snippet;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Bull_02: THREE.Mesh;
		};
		materials: {};
	};

	const gltf = useGltf<GLTFResult>('/models/undertow/Bull_02.glb');
</script>

<T.Group dispose={false} position={[ 0, 0, -7 ]} >
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Bull_02.geometry} material={gltf.nodes.Bull_02.material} position={[ -5.9, 0, -6 ]}  />
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.()}
</T.Group>
