<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static\models\undertow\Zardoz_01.glb
-->

<script lang="ts">
	import type { Props } from '@threlte/core';
	import type * as THREE from 'three';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const gltf = useGltf('/models/undertow/Zardoz_01.glb');
</script>

<T.Group bind:ref dispose={false} {...props} position={[ -4.8, 0, 0 ]}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Zardoz_01.geometry} material={gltf.nodes.Zardoz_01.material} position={[ 1.3, -1.1, -3.3 ]} />
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
