<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\mpalc\OneDrive\Desktop\_projects\Venezia 2025\_resources\undertow\Crocodile_01.glb --types --S
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, useThrelte, type Props } from '@threlte/core';
	import { meshBounds, OrbitControls, useGltf } from '@threlte/extras';
	import { interactivity } from '@threlte/extras';
	import { PerspectiveCamera } from 'three';
	import { PI } from 'three/tsl';

	interactivity();

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Crocodile_01: THREE.Mesh;
		};
		materials: {};
	};

	const gltf = useGltf<GLTFResult>('/models/undertow/Crocodile_01.glb');
	const { camera } = useThrelte();
	let localCamera: undefined | PerspectiveCamera = $state();

	function setLocalCamera() {
		console.log('doubleclick');
		if (localCamera instanceof PerspectiveCamera) {
			camera.set(localCamera);
		}
	}
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Crocodile_01.geometry}
			material={gltf.nodes.Crocodile_01.material}
			ondblclick={(e: any) => setLocalCamera()}
		/>
		<T.PerspectiveCamera bind:ref={localCamera} position={[0, 1, 0]}>
			<OrbitControls enableDamping />
		</T.PerspectiveCamera>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
