<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\_projects-local\Venezia 2025\venezia-2025\static\models\various\BT_02.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Head_1: THREE.Mesh
      Head_2: THREE.Mesh
      Face_1: THREE.Mesh
      Face_2: THREE.Mesh
      Face_3: THREE.Mesh
      Face_4: THREE.Mesh
      Eyes: THREE.Mesh
      Sphere: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>(
    '/C:\_projects-local\Venezia 2025\venezia-2025\static\models\various\BT_02.glb'
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 0.02, 0.27]}
      scale={[0.78, 0.92, 0.68]}
    >
      <T.Mesh
        geometry={gltf.nodes.Face_1.geometry}
        material={gltf.nodes.Face_1.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Face_2.geometry}
        material={gltf.nodes.Face_2.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Face_3.geometry}
        material={gltf.nodes.Face_3.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Face_4.geometry}
        material={gltf.nodes.Face_4.material}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Eyes.geometry}
      material={gltf.nodes.Eyes.material}
      position={[0.14, 0.09, 0.13]}
      rotation={[-Math.PI, 0, 0]}
      scale={[0.13, 0.12, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Sphere.geometry}
      material={gltf.nodes.Sphere.material}
      position={[0.14, 0.08, 0.42]}
      scale={0.22}
    />
    <T.DirectionalLight
      intensity={2.27}
      decay={2}
      color="#ff9d22"
      position={[-0.71, 0.89, 0.95]}
      rotation={[-1.04, -0.75, -0.44]}
    />
    <T.Mesh
      geometry={gltf.nodes.Head_1.geometry}
      material={gltf.nodes.Head_1.material}
    />
    <T.Mesh
      geometry={gltf.nodes.Head_2.geometry}
      material={gltf.nodes.Head_2.material}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
