<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\_projects-local\Venezia 2025\venezia-2025\static\models\architecture\Optimize_02.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Lathe_1011: THREE.Mesh
      Cone_1001_1: THREE.Mesh
      Cone_1001_2: THREE.Mesh
      Cone_1001_3: THREE.Mesh
      Cone_1001_4: THREE.Mesh
      Box005_1: THREE.Mesh
      Box005_2: THREE.Mesh
      Box005_3: THREE.Mesh
      Box005_4: THREE.Mesh
      Box007_1: THREE.Mesh
      Box007_2: THREE.Mesh
      Box007_3: THREE.Mesh
      Box007_4: THREE.Mesh
      Box007_5: THREE.Mesh
      Lathe_5001_1: THREE.Mesh
      Lathe_5001_2: THREE.Mesh
    }
    materials: {
      ['Material_2.003']: THREE.MeshStandardMaterial
      ['Material_0.003']: THREE.MeshStandardMaterial
      ['Material_1.003']: THREE.MeshStandardMaterial
      ['Material_3.003']: THREE.MeshStandardMaterial
      ['Material_4.003']: THREE.MeshStandardMaterial
      ['Material_6.003']: THREE.MeshStandardMaterial
      ['Material_5.003']: THREE.MeshStandardMaterial
      ['Material_7.001']: THREE.MeshStandardMaterial
      ['Material_8.001']: THREE.MeshStandardMaterial
      ['Material_13.001']: THREE.MeshStandardMaterial
      ['Material_9.001']: THREE.MeshStandardMaterial
      ['Material_10.001']: THREE.MeshStandardMaterial
      ['Material_11.001']: THREE.MeshStandardMaterial
      ['Material_12.001']: THREE.MeshStandardMaterial
      ['Material_15.001']: THREE.MeshStandardMaterial
      ['Material_14.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/C:\_projects-local\Venezia 2025\venezia-2025\static\models\architecture\Optimize_02.glb'
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group position={[-0.72, -3.94, 0]}>
      <T.Group
        position={[0.72, 3.64, 0]}
        scale={[0.88, 0.77, 0.88]}
      >
        <T.Mesh
          geometry={gltf.nodes.Lathe_1011.geometry}
          material={gltf.materials['Material_2.003']}
          position={[0, -1.39, 0]}
          scale={[0.29, 0.29, 0.03]}
        />
      </T.Group>
      <T.Group
        position={[0.72, 3.07, 0.11]}
        rotation={[0, 0.32, 0]}
        scale={[2.34, 1.3, 2.34]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cone_1001_1.geometry}
          material={gltf.materials['Material_0.003']}
        />
        <T.Mesh
          geometry={gltf.nodes.Cone_1001_2.geometry}
          material={gltf.materials['Material_1.003']}
        />
        <T.Mesh
          geometry={gltf.nodes.Cone_1001_3.geometry}
          material={gltf.materials['Material_3.003']}
        />
        <T.Mesh
          geometry={gltf.nodes.Cone_1001_4.geometry}
          material={gltf.materials['Material_4.003']}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, -1.53, 0]}>
      <T.Group
        position={[-0.18, -0.68, 0.15]}
        rotation={[0, 0.32, 0]}
        scale={[1, 1.21, 1]}
      >
        <T.Mesh
          geometry={gltf.nodes.Box005_1.geometry}
          material={gltf.materials['Material_6.003']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box005_2.geometry}
          material={gltf.materials['Material_5.003']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box005_3.geometry}
          material={gltf.materials['Material_7.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box005_4.geometry}
          material={gltf.materials['Material_8.001']}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, -2.84, 0]}>
      <T.Group
        position={[0, -5.07, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.65}
      >
        <T.Mesh
          geometry={gltf.nodes.Box007_1.geometry}
          material={gltf.materials['Material_13.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box007_2.geometry}
          material={gltf.materials['Material_9.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box007_3.geometry}
          material={gltf.materials['Material_10.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box007_4.geometry}
          material={gltf.materials['Material_11.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Box007_5.geometry}
          material={gltf.materials['Material_12.001']}
        />
      </T.Group>
    </T.Group>
    <T.Group
      position={[-0.36, -3.61, 0.36]}
      scale={0.07}
    >
      <T.Group position={[9.61, 0, -9.72]}>
        <T.Mesh
          geometry={gltf.nodes.Lathe_5001_1.geometry}
          material={gltf.materials['Material_15.001']}
        />
        <T.Mesh
          geometry={gltf.nodes.Lathe_5001_2.geometry}
          material={gltf.materials['Material_14.001']}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
