<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\_projects-local\Venezia 2025\venezia-2025\static\models\various\Archway_Multiple_01.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			[key: string]: THREE.Mesh; // Generalize node types as they are all meshes here
		};
		materials: {};
	};

	const gltf = useGltf<GLTFResult>('/models/various/Archway_Multiple_01.glb');

	const nodes = $derived.by(() => {
		if (!$gltf || !$gltf.nodes) {
			return [];
		}
		return Object.values($gltf.nodes) as THREE.Mesh[];
	});

	$effect.pre(() => {
		console.log(`Nodes loaded (reactive check): ${nodes.length}`);
		if (nodes.length > 0) {
			console.log('Successfully loaded nodes!');
			nodes.forEach((node) => {
				if (node.type == 'Mesh') {
					console.log(node);
				}
			});
		}
	});
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[9.21, -0.32, 15.85]}>
			{#each nodes as node}
				{#if node.type == 'Mesh'}
					<T.Mesh geometry={node.geometry} material={node.material} />
				{/if}
			{/each}
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
