<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static\models\undertow\Zardoz_01.glb
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { meshBounds } from '@threlte/extras';
	import { Spring } from 'svelte/motion';
	import { interactivity } from '@threlte/extras';

	interactivity()
	const scale = new Spring(1)
	let { fallback, error, children, ref = $bindable(), ...props } = $props();
	const gltf = useGltf('/models/undertow/Zardoz_01.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh 
			geometry={gltf.nodes.Zardoz_01.geometry} 
			material={gltf.nodes.Zardoz_01.material}  
			raycast={meshBounds}
			scale ={scale.current}
			onpointerenter={()=>{
				scale.target = 1.5
			}}
			onpointerleave={()=>{
				scale.target = 1
			}}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
