<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static\models\undertow\Zardoz_01.glb
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { meshBounds } from '@threlte/extras';
	import { interactivity } from '@threlte/extras';
	import { TransformControls } from '@threlte/extras';
	import { Text } from '@threlte/extras';

	interactivity();
	
	let showTransformControls = $state(true)
	let { fallback, error, children, ref = $bindable(), ...props } = $props();
	const gltf = useGltf('/models/undertow/Zardoz_01.glb');
</script>



<TransformControls 
	showX={showTransformControls} 
	showY={showTransformControls}
	showZ={showTransformControls}
>
<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh 
			geometry={gltf.nodes.Zardoz_01.geometry} 
			material={gltf.nodes.Zardoz_01.material}  
			raycast={meshBounds}
			ondblclick={(e: any) => 
				showTransformControls = !showTransformControls
			}
		
		>
		</T.Mesh>
		<Text
			text ="Double click to show or hide Transform Controls"
			color="black"
			anchorX="50%"
			anchorY="650%"
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
</TransformControls>

