<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\_projects-local\Venezia 2025\venezia-2025\static\models\various\ArchwayMultiple_01-m.glb
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/models/various/ArchwayMultiple_01-m.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[9.21, -0.47, 15.98]} scale={0.53}>
			<T.Mesh geometry={gltf.nodes.Archway_1.geometry} material={gltf.nodes.Archway_1.material} />
			<T.Mesh geometry={gltf.nodes.Archway_2.geometry} material={gltf.nodes.Archway_2.material} />
			<T.Mesh geometry={gltf.nodes.Archway_3.geometry} material={gltf.nodes.Archway_3.material} />
			<T.Mesh geometry={gltf.nodes.Archway_4.geometry} material={gltf.nodes.Archway_4.material} />
			<T.Mesh geometry={gltf.nodes.Archway_5.geometry} material={gltf.nodes.Archway_5.material} />
			<T.Mesh geometry={gltf.nodes.Archway_6.geometry} material={gltf.nodes.Archway_6.material} />
			<T.Mesh geometry={gltf.nodes.Archway_7.geometry} material={gltf.nodes.Archway_7.material} />
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
