<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static\models\undertow\Zardoz_01.glb
-->

<script lang='ts'>
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { meshBounds } from '@threlte/extras';
	import { Spring } from 'svelte/motion';
	import { interactivity } from '@threlte/extras';


	import type * as THREE from 'three';
	
	import type { Snippet } from 'svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	interactivity()
	const scale = new Spring(1)
	const gltf = useGltf('/models/undertow/Zardoz_01.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh 
			geometry={gltf.nodes.Zardoz_01.geometry} 
			material={gltf.nodes.Zardoz_01.material}  
			raycast={meshBounds}
			scale ={scale.current}
			onpointerenter={()=>{
				scale.target = 1.5
			}}
			onpointerleave={()=>{
				scale.target = 1
			}}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
