<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\mpalc\OneDrive\Desktop\_projects\Venezia 2025\venezia-2025\static\models\undertow\BurntBoy_01.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import {interactivity, TransformControls, useGltf, meshBounds} from '@threlte/extras';
	import type { TransformControlsMode } from 'three/examples/jsm/Addons.js';
	import type { ModelName } from '../types';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		name = 'BurntBoy_01',
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
		name?: ModelName;
	} = $props();

	type GLTFResult = {
		nodes: {
			BurntBoy_01: THREE.Mesh;
		};
		materials: {};
	};
	interactivity();

	let showTransformControls: boolean = $state(false);
	let transformControlsMode: TransformControlsMode = $state('translate');

	const gltf = useGltf<GLTFResult>('/models/undertow/BurntBoy_01.glb');
</script>

<T.Group bind:ref dispose={false} name={name} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<TransformControls
			showX={showTransformControls}
			showY={showTransformControls}
			showZ={showTransformControls}
			mode={transformControlsMode}
		>
			<T.Mesh
				geometry={gltf.nodes.BurntBoy_01.geometry}
				material={gltf.nodes.BurntBoy_01.material}
				raycast={meshBounds}
				ondblclick={(e: any) => (showTransformControls = !showTransformControls)}
			/>
		</TransformControls>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
