<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static\models\undertow\Zardoz_01.glb
-->

<script lang="ts">
	import type { Props } from '@threlte/core';
	import type * as THREE from 'three';
	import { T } from '@threlte/core';
	import { interactivity, meshBounds, TransformControls, useGltf, Text } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	interactivity();
	let showTransformControls = $state(true)

	const gltf = useGltf('/models/undertow/Zardoz_01.glb');
</script>



<TransformControls 
	showX={showTransformControls} 
	showY={showTransformControls}
	showZ={showTransformControls}
	position={[0,0,0]}
>
<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh 
			geometry={gltf.nodes.Zardoz_01.geometry} 
			material={gltf.nodes.Zardoz_01.material}  
			raycast={meshBounds}
			ondblclick={(e: any) => 
				showTransformControls = !showTransformControls
			}
		>
		</T.Mesh>
		<Text
			text ="Double click to show or hide Transform Controls"
			color="black"
			anchorX="50%"
			anchorY="650%"
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
</TransformControls>

