<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static\models\undertow\Leone_01.glb -t
-->

<script lang="ts">
				
	
import type * as THREE from 'three'
	
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> &  {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()

				

				

        type GLTFResult = {
    nodes: {
      Leone_01: THREE.Mesh
      
    }
    materials: {
      
    }
  }

        const gltf = useGltf<GLTFResult>('/models/undertow/Leone_01.glb')


</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Leone_01.geometry}
      material={gltf.nodes.Leone_01.material}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
		{@render children?.({ ref })}
	{/if}
</T.Group>
